### ISSUE TITLE
Contribution graph is too bright!

### ISSUE THREAD

**Issue by MichalPaszkiewicz** [amitmerchant1990/github-night-mode#1]
I will lose my night vision if I see anything white!

could we have

rect.day{
    opacity: 0.5;
}

or another solution to get rid of all those massive white sections?

Cheers!

**Comment by amitmerchant1990** [comment]
Yes! That would be a good idea. I'll try it out.

**Comment by amitmerchant1990** [comment]
@MichalPaszkiewicz 99c63b8303bdac088898b6c2aa58c67e8e12085f have solved this issue.

**Comment by MichalPaszkiewicz** [comment]
sweet, thanks!
